accounts/urls.py
"""Defining URL patterns for accounts"""

from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    # Include default auth urls
    path('', include('django.contrib.auth.urls')),
    # Registration page
    path('register/', views.register, name='register'),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""
from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Topics page
    path('topics/', views.topics, name='topics'),
    # Individual Topic page to display all its entries
    path('topic/<int:topic_id>/', views.topic, name='topic'),
    # Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page for adding a new entry
    path('new_entry/<int:topic_id>', views.new_entry, name='new_entry'),
    # Page for editing an entry
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
    # Page for editing a topic
    path('edit_topic/<int:topic_id>/', views.edit_topic, name='edit_topic'),
]

ll_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('learning_logs.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """A topic the user is learning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    visibility = models.BooleanField(default=False)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text


class Entry(models.Model):
    """Something specific learned about a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a simple string representing the entry."""
        if len(self.text) > 50:  # Ex.18-2
            return f"{self.text[:50]}..."
        else:
            return self.text

learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text', 'visibility']
        labels = {'text': '', 'visibility': 'make public?'}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(
            attrs={'cols': 80, 'placeholder': 'Type your content here'})}

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Register a new user"""

    # To prevent a logged in user from accessing the registration URL
    if request.user.is_authenticated:
        return redirect('learning_logs:index')

    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('learning_logs:index')

    form.fields['username'].help_text = None
    form.fields['password1'].help_text = None
    form.fields['password2'].help_text = None

    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.http import Http404


def index(request):
    """The home page for Learning Log."""
    entries = Entry.objects.order_by('-date_added')
    public_entries = []
    for entry in entries:
        if entry.topic.visibility:
            public_entries.append(entry)
    count = len(public_entries)
    if count == 0:
        context = {'recent_entries': []}
    elif count == 1:
        context = {'recent_entries': [public_entries[0]]}
    else:
        context = {'recent_entries': [public_entries[0], public_entries[1]]}
    return render(request, 'learning_logs/index.html', context)


def topics(request):
    """Page to list all topics"""
    topics = Topic.objects.order_by('date_added')

    public_topics = []
    private_topics = []
    owner_topics = []

    for topic in topics:
        if request.user.is_authenticated:
            if topic.owner == request.user:
                if topic.visibility == False:
                    private_topics.append(topic)
                else:
                    owner_topics.append(topic)
            else:
                if topic.visibility == True:
                    public_topics.append(topic)
        else:
            if topic.visibility == True:
                public_topics.append(topic)

    context = {'public_topics': public_topics,
               'private_topics': private_topics, 'owner_topics': owner_topics}
    return render(request, 'learning_logs/topics.html', context)


def topic(request, topic_id):
    """Display all the entries in a particular topic"""
    topic = Topic.objects.get(id=topic_id)
    if topic.visibility == False:
        check_topic_owner(request.user, topic.owner)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """adds a new topic"""
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """adds a new entry"""
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(request.user, topic.owner)  # Ex_19-4
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """edit an existing entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    check_topic_owner(request.user, topic.owner)
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


@login_required
def edit_topic(request, topic_id):
    """edit an existing topic"""
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(request.user, topic.owner)
    if request.method != 'POST':
        form = TopicForm(instance=topic)
    else:
        form = TopicForm(instance=topic, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topics')

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_topic.html', context)


def check_topic_owner(user, owner):  # Ex_19-3
    """checks whether the topic matches the currently logged-in user"""
    if owner != user:
        raise Http404

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Learning Log</title>

  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
        aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics</a>
          </li>
        </ul> <!-- End of links on left side of navbar -->

        <!-- Account-related links -->
        <ul class="navbar-nav ms-auto mb-2 mb-md-0">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text me-2">Hello, {{ user.username }}.
            </span>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:register' %}">
              Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">
              Log in</a>
          </li>
          {% endif %}
        </ul> <!-- End of account-related links -->

        {% if user.is_authenticated %}
        <form action="{% url 'accounts:logout' %}" method='post'>
          {% csrf_token %}
          <button name='submit' class='btn btn-outline-secondary btn-sm'>
            Log out</button>
        </form>
        {% endif %}

      </div> <!-- Closes collapsible parts of navbar -->
    </div> <!-- Closes navbar's container -->
  </nav> <!-- End of navbar -->
  <main class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>
</body>

</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id%}">{{ topic }}</a></p>
<p>Edit entry:</p>
<form action="{% url 'learning_logs:edit_entry' entry.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_div }}
    <button name="submit">Edit entry</button>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/edit_topic.html
{% extends 'learning_logs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
<h2>Edit Topic: {{topic.text}}</h2>
{% endblock page_header %}

{% block content %}
<form action="{% url 'learning_logs:edit_topic' topic.id %}" method='post'>
  {% csrf_token %}
  {% bootstrap_form form %}
  {% bootstrap_button button_type="submit" content="Save Changes" %}
</form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}
{% block page_header %}
<div class="p-3 mb-4 bg-light border rounded-3">
  <div class="container-fluid py-4">
    <h1 class="display-3">Track your learning.</h1>

    <p class="lead">Make your own Learning Log, and keep a list of the topics you're learning about. Whenever you learn
      something new about a topic, make an entry summarizing what you've learned.</p>
    {% if request.user.is_authenticated %}
    <a class="btn btn-primary btn-lg mt-1" href="{% url 'learning_logs:new_topic' %}">Create a new Topic &raquo;</a>
    {% else %}
    <a class="btn btn-primary btn-lg mt-1" href="{% url 'accounts:register' %}">Register &raquo;</a>
    {% endif %}
  </div>
</div>
{% endblock page_header %}

{% block content %}
{% if recent_entries %}
<div class="py-1 mb-2 ">
  <h4>Recently added entries:</h4>
</div>

{% for entry in recent_entries %}
<div class="card mb-3">
  <!-- Card header with timestamp and edit link -->
  <h6 class="card-header pb-2 pt-3">
    <a href="{% url 'learning_logs:topic' entry.topic.id %}">{{entry.topic.text}}</a> |
    <small><i>{{entry.date_added|date:'M d, Y - H:i'}}</i></small>
  </h6>
  <!-- Card body with entry text -->
  <div class="card-body pb-1" style="text-align: justify;">
    {{ entry.text|truncatewords:50|linebreaks }}
    <b>by {{entry.topic.owner}}</b>
  </div>
</div>
{% endfor %}
{% endif %}

{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
<h2><a href="{% url 'learning_logs:topic' topic.id%}">{{ topic }}</a> - Add a new entry</h2>
{% endblock page_header %}


{% block content %}
<form action="{% url 'learning_logs:new_entry' topic.id %}" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% bootstrap_button button_type="submit" content="Add Entry" %}
</form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
<h2>Add a new Topic:</h2>
{% endblock page_header %}

{% block content %}
<form action="{% url 'learning_logs:new_topic' %}" method='post'>
  {% csrf_token %}
  {% bootstrap_form form %}
  {% bootstrap_button button_type="submit" content="Add Topic" %}
</form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
<h1>{{ topic.text }}</h1>
{% if not topic.visibility %}
<p>This topic is private, want to <a href="{% url 'learning_logs:edit_topic' topic.id%}">edit</a>?</p>
{% else %}
{% if not request.user.is_authenticated or request.user == topic.owner%}
<a href="{% url 'learning_logs:edit_topic' topic.id%}">Edit Topic</a>
{% endif %}
{% endif %}
{% endblock page_header %}

{% block content %}
{% if not request.user.is_authenticated or request.user == topic.owner%}
<p>
  <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
</p>
{% endif %}


{% for entry in entries %}
<div class="card mb-3">
  <!-- Card header with timestamp and edit link -->
  <h4 class="card-header">
    {{ entry.date_added|date:'M d, Y H:i' }}
    {% if not request.user.is_authenticated or request.user == topic.owner%}
    <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
        edit entry</a></small>
    {% endif %}
  </h4>
  <!-- Card body with entry text -->
  <div class="card-body">{{ entry.text|linebreaks }}</div>
</div>
{% empty %}
<p>There are no entries for this topic yet.</p>
{% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
<h1>Topics</h1>
{% endblock page_header %}

{% block content %}
{% if request.user.is_authenticated %}
<h5 class="card-header">Your Topics:</h5>
<ul class="list-group border-bottom pb-2 mb-4">
  {% for topic in owner_topics %}
  <li class="list-group-item border-0">
    <a href="{% url 'learning_logs:topic' topic.id %}">
      {{ topic.text }}</a>
  </li>
  {% empty %}
  <li class="list-group-item border-0">No topics have been added yet.</li>
  {% endfor %}
</ul>
{% endif %}
<h5 class="card-header">Public Topics:</h5>
<ul class="list-group border-bottom pb-2 mb-4">
  {% for topic in public_topics %}
  <li class="list-group-item border-0">
    <a href="{% url 'learning_logs:topic' topic.id %}">
      {{ topic.text }}</a>
  </li>
  {% empty %}
  <li class="list-group-item border-0">No topics have been added yet.</li>
  {% endfor %}
</ul>
{% if private_topics %}
<h5 class="card-header">Private Topics:</h5>
<ul class="list-group border-bottom pb-2 mb-4">
  {% for topic in private_topics %}
  <li class="list-group-item border-0">
    <a href="{% url 'learning_logs:topic' topic.id %}">
      {{ topic.text }}</a>
  </li>
  {% empty %}
  <li class="list-group-item border-0">No topics have been added yet.</li>
  {% endfor %}
</ul>
{% endif %}

<a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>

{% endblock content %}